# Peer identity: /p2p/12D3KooWAogX16pe24rWAUi3bYYC2dhQ8rCKRs1oQDJJcq28Hc9M
# Ethereum address: 0x2a0D87eA3a9E0ca33Ddd4a62C33878b58152effE


InstanceID = 442
# If it's empty, we use the standard PG_ environment variables
DatabaseURL		= "postgres://postgres@db:5432/keyper-3"
HTTPEnabled = false
HTTPListenAddress = ':3000'

[P2P]
P2PKey = 'CAESQKtWIpuCUYIG7VvWTVf5O8Mw93TyEOtjD8I8V/cW+7zXDq7ajNbrHANBxHL/zekXNgbXEQr95RGbY5RImSM2T+A='
ListenAddresses = ["/ip4/0.0.0.0/tcp/23000"]
# Overwrite p2p boostrap nodes
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]
Environment = 'production'

[Optimism]
PrivateKey = '83b6122c38b58e37ce42adafd43e7b402e19f4413ce6de9dc9219f50d71c3768'
# The op-geth JSON RPC endpoint
JSONRPCURL = 'ws://l2:8546/'

[Shuttermint]
ShuttermintURL		= "http://chain-3-validator:26657"
ValidatorPublicKey = "79acab5169694e130cd1e9713270540e8dd8697d34f1c87e27be1a263062145e"
EncryptionKey = '2377fd4943e78a1f16dabb0584f6aacdb14f118fe37a5dbddf540a54b071c6c0'
DKGPhaseLength = 8
DKGStartBlockDelta = 200
